apiVersion: v1
kind: ConfigMap
metadata:
  name: drift-configmap
  namespace: mlops-drift
data:
  MLFLOW_TRACKING_URI: "http://<CLUSTER-IP>:<MLFLOW-PORT>"
  KAFKA_BOOTSTRAP_SERVERS: "<CLUSTER-IP>:<KAFKA-SERVICE-PORT>"