apiVersion: v1
kind: Service
metadata:
  name: drift-detector-service
  namespace: mlops-drift
spec:
  selector:
    app: drift-detector-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
