apiVersion: v1
kind: Service
metadata:
  name: drift-detector-service
  namespace: mlops-drift
  labels:
    app: drift-detector-app
spec:
  selector:
    app: drift-detector-app
  ports:
  - name: metrics
    protocol: TCP
    port: 8000
    targetPort: 8000
