apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: seldon
spec:
  type: LoadBalancer
  selector:
    app: mlflow-tracking-server-pods
  ports:
    - name: ''
      protocol: TCP
      port: 5000
