apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-configmap
  namespace: seldon
data:
  DB_NAME: "mlflow-tracking-server"
  DB_URL: "postgresql-mlflow.seldon.svc.cluster.local"
  DB_USERNAME: "postgres"
