apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlops-mlflow
spec:
  type: NodePort
  selector:
    app: mlflow-tracking-server-pods
  ports:
    - name: ''
      protocol: TCP
      port: 5000
      nodePort: <MLFLOW-PORT>
